name: DuckMode
depends: [WorldEdit]
author: glatteis
authors: [IronMansVater]
main: me.glatteis.duckmode.DuckMain
version: 0.5 beta snapshot

commands:
    start:
       description: Starts the game manually
       usage: /start
    addsecrethats:
       description: Very Secret Command! Unlocks no hats!
       usage: The usage of this mysterious command is very secret!